import Link from 'next/link';
import { cookies } from 'next/headers';
import { fetchSites } from '../../lib/api';
import SiteActions from '../../components/SiteActions';

function scoreLabel(score: number | null) {
  return score === null ? 'Non analysé' : score >= 80 ? 'Bon' : score >= 50 ? 'À améliorer' : 'Prioritaire';
}

export default async function SitesPage() {
  const sites = await fetchSites((await cookies()).toString());
  const analysed = sites.filter((site) => site.last_scan_score !== null);
  const average = analysed.length ? analysed.reduce((total, site) => total + (site.last_scan_score ?? 0), 0) / analysed.length : 0;
  return <div className="space-y-8">
    <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[var(--color-primary)]">Vue d’ensemble</p><h1 className="mt-2 font-display text-3xl font-bold text-[#102d4f]">Votre accessibilité, en clair.</h1><p className="mt-2 max-w-xl text-[var(--color-muted)]">Surveillez les parcours essentiels et donnez à votre équipe un cap concret pour chaque correction.</p></div><Link href="/sites/new" className="inline-flex min-h-12 items-center justify-center rounded-lg px-5 font-semibold shadow-sm transition-colors hover:bg-[#102d4f] focus-ring" style={{ backgroundColor: '#1457a6', color: '#ffffff' }}>+ Ajouter un site</Link></section>
    <section aria-label="Indicateurs clés" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Score moyen" value={analysed.length ? `${average.toFixed(0)}/100` : '—'} detail={analysed.length ? 'sur les sites analysés' : 'Lancez votre premier scan'} accent="green" /><Stat label="Sites suivis" value={String(sites.length)} detail="dans votre workspace" accent="blue" /><Stat label="Scans disponibles" value={String(analysed.length)} detail="dernier scan par site" accent="amber" /><Stat label="À surveiller" value={String(sites.filter((site) => site.last_scan_score !== null && site.last_scan_score < 80).length)} detail="score inférieur à 80" accent="red" /></section>
    <section aria-labelledby="sites-title"><div className="mb-4"><h2 id="sites-title" className="font-display text-xl font-bold text-[#102d4f]">Sites surveillés</h2><p className="text-sm text-[var(--color-muted)]">Les dernières données connues par domaine.</p></div>{sites.length === 0 ? <div className="rounded-2xl border border-dashed border-[var(--color-border)] bg-white p-10 text-center text-[var(--color-muted)]">Aucun site enregistré pour l'instant.</div> : <div className="overflow-x-auto rounded-2xl border border-[var(--color-border)] bg-white"><div className="hidden min-w-[1200px] grid-cols-[1.45fr_0.65fr_0.8fr_0.8fr_0.9fr_1.3fr] gap-4 border-b border-[var(--color-border)] bg-[#f7faff] px-5 py-3 text-xs font-bold uppercase tracking-wide text-[var(--color-muted)] md:grid"><span>Site</span><span>Score</span><span>Dernier scan</span><span>Type de scan</span><span>État</span><span>Actions</span></div><div className="divide-y divide-[var(--color-border)]">{sites.map((site) => { const scanMode = site.scan_mode ?? site.last_scan_mode; const scanModeLabel = scanMode === 'full_site' ? 'Site complet' : scanMode === 'single_page' ? 'Page unique' : '—'; return <div key={site.id} className="grid gap-3 px-5 py-4 md:min-w-[1200px] md:grid-cols-[1.45fr_0.65fr_0.8fr_0.8fr_0.9fr_1.3fr] md:items-center md:gap-4"><div><p className="font-semibold text-[#102d4f]">{site.name}</p><p className="break-all font-mono text-xs text-[var(--color-muted)]">{site.url}</p></div><div><span className="mr-2 text-xs text-[var(--color-muted)] md:hidden">Score</span><strong className="font-mono text-lg text-[#102d4f]">{site.last_scan_score === null ? '—' : `${site.last_scan_score.toFixed(0)}/100`}</strong></div><div className="text-sm text-[var(--color-muted)]"><span className="mr-2 text-xs md:hidden">Dernier scan</span>{site.last_scan_date ? new Date(site.last_scan_date).toLocaleDateString('fr-FR') : 'Jamais'}</div><div className="text-sm font-semibold text-[#294967]"><span className="mr-2 text-xs font-normal text-[var(--color-muted)]">Type</span>{scanModeLabel}</div><div className="text-sm text-[var(--color-muted)]"><span className="mr-2 text-xs md:hidden">État</span>{scoreLabel(site.last_scan_score)}</div><SiteActions site={site} /></div>; })}</div></div>}</section>
  </div>;
}

function Stat({ label, value, detail, accent }: { label: string; value: string; detail: string; accent: string }) { return <article className="rounded-2xl border border-[var(--color-border)] bg-white p-5"><span className={`mb-5 block h-2 w-10 rounded-full ${accent === 'green' ? 'bg-[#49b883]' : accent === 'blue' ? 'bg-[#4f91d1]' : accent === 'amber' ? 'bg-[#e3a72f]' : 'bg-[#cf5648]'}`} aria-hidden="true" /><p className="text-sm font-semibold text-[var(--color-muted)]">{label}</p><p className="mt-2 font-display text-3xl font-bold text-[#102d4f]">{value}</p><p className="mt-1 text-xs text-[var(--color-muted)]">{detail}</p></article>; }
