ALTER TABLE scans ADD COLUMN IF NOT EXISTS progress integer NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS current_step text NOT NULL DEFAULT 'pending';
ALTER TABLE scans ADD COLUMN IF NOT EXISTS error text;