services:
  db:
    image: postgres:16
    container_name: wap_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accessibility
    ports:
      - "5432:5432"
    volumes:
      - wap_db_data:/var/lib/postgresql/data

volumes:
  wap_db_data:
