import Link from 'next/link';
import { cookies } from 'next/headers';
import { fetchReport, ReportViolation } from '../../../lib/api';

const labels: Record<string, string> = { critical: 'Bloquante', serious: 'Majeure', moderate: 'Modérée', minor: 'Mineure' };

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const report = await fetchReport(id, (await cookies()).toString());
  const content = report.content!;
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8002';
  return <div className="space-y-8 pb-12">
    <div><Link href="/reports" className="text-sm font-semibold text-brand hover:underline focus-ring">← Tous les rapports</Link><p className="mt-6 text-sm font-semibold uppercase tracking-[0.12em] text-[var(--color-primary)]">AccessIQ</p><h1 className="mt-2 font-display text-3xl font-bold text-[#102d4f]">Accessibility Remediation Report</h1><p className="mt-2 break-all text-[var(--color-muted)]">{report.website_url}</p></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Score', report.score === null ? 'N/A' : `${report.score}/100`], ['Violations', content.total], ['Pages analysées', content.pages_scanned], ['Pages en erreur', content.pages_failed]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-[var(--color-border)] bg-white p-5"><p className="text-sm text-[var(--color-muted)]">{label}</p><p className="mt-2 font-display text-2xl font-bold text-[#102d4f]">{value}</p></article>)}</section>
    <section className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><h2 className="font-display text-xl font-bold text-[#102d4f]">Résumé des violations</h2><div className="mt-5 grid gap-4 sm:grid-cols-4">{(['critical', 'serious', 'moderate', 'minor'] as const).map((impact) => <div key={impact}><p className="text-sm text-[var(--color-muted)]">{labels[impact]}</p><p className="mt-1 font-mono text-2xl font-semibold">{content[impact]}</p></div>)}</div></section>
    <section aria-labelledby="findings-title"><h2 id="findings-title" className="font-display text-xl font-bold text-[#102d4f]">Violations détaillées</h2><div className="mt-4 space-y-5">{content.violations.length === 0 ? <div className="rounded-2xl border border-dashed border-[var(--color-border)] bg-white p-8 text-[var(--color-muted)]">0 violation détectée.</div> : content.violations.map((violation) => <ViolationBlock key={violation.id} violation={violation} />)}</div></section>
    <div className="flex flex-wrap gap-4"><a href={`${apiUrl}/api/reports/${report.id}/download`} className="inline-flex min-h-11 items-center justify-center rounded-md bg-[var(--color-primary)] px-4 py-2 font-semibold text-white focus-ring" style={{ color: '#ffffff' }}>Télécharger le PDF</a><Link href={`/scans/${report.scan_id}`} className="inline-flex min-h-11 items-center justify-center rounded-md border border-[var(--color-border)] px-4 py-2 font-semibold text-[#102d4f] focus-ring">Voir le scan</Link></div>
  </div>;
}

function ViolationBlock({ violation }: { violation: ReportViolation }) {
  const diagnostic = violation.diagnostic;
  const location = violation.source_file ? `${violation.source_file}${violation.source_line ? `:${violation.source_line}` : ''}${violation.source_column ? `:${violation.source_column}` : ''}` : 'Non disponible.';
  return <article className="rounded-2xl border border-[var(--color-border)] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-[var(--color-muted)]">{labels[violation.impact] ?? violation.impact}</p><h3 className="mt-1 font-display text-lg font-bold text-[#102d4f]">{violation.rule}</h3></div><a href={violation.page_url} target="_blank" rel="noreferrer" className="max-w-full break-all text-sm font-semibold text-brand hover:underline focus-ring">{violation.page_url}</a></div><dl className="mt-5 grid gap-4 text-sm md:grid-cols-2"><div><dt className="font-semibold">Problème</dt><dd className="mt-1 text-[var(--color-muted)]">{violation.message || 'Description non disponible.'}</dd></div><div><dt className="font-semibold">Élément concerné</dt><dd className="mt-1 break-all font-mono text-xs text-[var(--color-muted)]">{violation.element || 'Non disponible.'}</dd></div><div><dt className="font-semibold">Référence WCAG</dt><dd className="mt-1 text-[var(--color-muted)]">{Array.isArray(violation.wcag) ? violation.wcag.join(', ') : violation.wcag || 'Non disponible.'}</dd></div><div><dt className="font-semibold">Localisation dans le code</dt><dd className="mt-1 break-all font-mono text-xs text-[var(--color-muted)]">{location}</dd></div></dl><div className="mt-6 border-t border-[var(--color-border)] pt-5"><h4 className="font-semibold">Correction proposée par l’IA</h4><p className="mt-2 text-sm text-[var(--color-muted)]">{violation.explanation || diagnostic?.explication_simple || 'Correction IA non disponible pour cette violation.'}</p>{violation.recommendation && <p className="mt-3 text-sm"><strong>Recommandation : </strong>{violation.recommendation}</p>}{(violation.corrected_code || violation.fix?.code_diff) && <div className="mt-4"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-[var(--color-muted)]">Code proposé</p><pre className="overflow-auto rounded-lg bg-[#102d4f] p-4 text-xs text-white"><code>{violation.corrected_code || violation.fix?.code_diff}</code></pre></div>}</div></article>;
}