import Link from 'next/link';
import { cookies } from 'next/headers';
import { fetchReports } from '../../lib/api';

export default async function ReportsPage() {
	const reports = await fetchReports((await cookies()).toString());
	const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8002';
	return <div className="space-y-8">
		<header><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[var(--color-primary)]">Pilotage</p><h1 className="mt-2 font-display text-3xl font-bold text-[#102d4f]">Rapports</h1><p className="mt-2 text-[var(--color-muted)]">Tous les rapports d’accessibilité générés pour votre espace.</p></header>
		{reports.length === 0 ? <div className="rounded-2xl border border-dashed border-[var(--color-border)] bg-white p-10 text-center text-[var(--color-muted)]">Aucun rapport généré pour le moment.</div> : <div className="overflow-hidden rounded-2xl border border-[var(--color-border)] bg-white"><div className="hidden grid-cols-[1.5fr_0.7fr_0.7fr_0.8fr] gap-4 border-b border-[var(--color-border)] bg-[#f7faff] px-5 py-3 text-xs font-bold uppercase tracking-wide text-[var(--color-muted)] md:grid"><span>Site</span><span>Score</span><span>Violations</span><span>Généré le</span></div><div className="divide-y divide-[var(--color-border)]">{reports.map((report) => <div key={report.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1.5fr_0.7fr_0.7fr_0.8fr] md:items-center md:gap-4"><div><p className="font-semibold text-[#102d4f]">{report.site_name}</p><p className="break-all font-mono text-xs text-[var(--color-muted)]">{report.website_url}</p></div><div><span className="mr-2 text-xs text-[var(--color-muted)] md:hidden">Score</span><strong>{report.score === null ? 'N/A' : `${report.score}/100`}</strong></div><div><span className="mr-2 text-xs text-[var(--color-muted)] md:hidden">Violations</span>{report.total_violations}</div><div className="flex flex-wrap items-center gap-3 text-sm"><span className="text-[var(--color-muted)]">{new Date(report.generated_at).toLocaleDateString('fr-FR')}</span><Link href={`/reports/${report.id}`} className="font-semibold text-brand hover:underline focus-ring">Voir</Link><a href={`${apiUrl}/api/reports/${report.id}/download`} className="font-semibold text-brand hover:underline focus-ring">Télécharger</a></div></div>)}</div></div>}
	</div>;
}